package generate

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/javiermolinar/lumbrera/internal/brain"
	"github.com/javiermolinar/lumbrera/internal/frontmatter"
	"github.com/javiermolinar/lumbrera/internal/git"
	"github.com/javiermolinar/lumbrera/internal/manifest"
	md "github.com/javiermolinar/lumbrera/internal/markdown"
)

type Files struct {
	Index     string
	Changelog string
	BrainSum  string
}

type PendingChangelogEntry struct {
	Date    time.Time
	Subject string
}

func FilesForRepo(repo string) (Files, error) {
	return FilesForRepoWithPending(repo, nil)
}

func FilesForRepoWithPending(repo string, pending []PendingChangelogEntry) (Files, error) {
	index, err := IndexForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	changelog, err := ChangelogForRepo(repo, pending)
	if err != nil {
		return Files{}, err
	}
	brainSum, err := manifest.ForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	return Files{Index: index, Changelog: changelog, BrainSum: brainSum}, nil
}

func WriteFiles(repo string, files Files) error {
	if err := os.WriteFile(filepath.Join(repo, brain.IndexPath), []byte(files.Index), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(repo, brain.ChangelogPath), []byte(files.Changelog), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(repo, brain.BrainSumPath), []byte(files.BrainSum), 0o644)
}

type indexDoc struct {
	Path  string
	Title string
}

func IndexForRepo(repo string) (string, error) {
	sources, err := indexDocs(repo, "sources")
	if err != nil {
		return "", err
	}
	wiki, err := indexDocs(repo, "wiki")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Index\n\n")
	b.WriteString("Generated by Lumbrera.\n\n")
	b.WriteString("## Sources\n\n")
	writeIndexTree(&b, "sources", sources, "No sources yet.")
	b.WriteString("\n## Wiki\n\n")
	writeIndexTree(&b, "wiki", wiki, "No wiki pages yet.")
	return b.String(), nil
}

type indexNode struct {
	Dirs  map[string]*indexNode
	Files []indexDoc
}

func newIndexNode() *indexNode {
	return &indexNode{Dirs: map[string]*indexNode{}}
}

func writeIndexTree(b *strings.Builder, root string, docs []indexDoc, emptyMessage string) {
	if len(docs) == 0 {
		b.WriteString(emptyMessage)
		b.WriteByte('\n')
		return
	}

	tree := newIndexNode()
	for _, doc := range docs {
		rel := strings.TrimPrefix(doc.Path, root+"/")
		parts := strings.Split(rel, "/")
		node := tree
		for _, dir := range parts[:len(parts)-1] {
			if dir == "" {
				continue
			}
			next := node.Dirs[dir]
			if next == nil {
				next = newIndexNode()
				node.Dirs[dir] = next
			}
			node = next
		}
		node.Files = append(node.Files, doc)
	}
	renderIndexNode(b, tree, 0)
}

type indexTreeEntry struct {
	Name  string
	Dir   *indexNode
	File  *indexDoc
	IsDir bool
}

func renderIndexNode(b *strings.Builder, node *indexNode, depth int) {
	entries := make([]indexTreeEntry, 0, len(node.Dirs)+len(node.Files))
	for name, dir := range node.Dirs {
		entries = append(entries, indexTreeEntry{Name: name, Dir: dir, IsDir: true})
	}
	for i := range node.Files {
		entries = append(entries, indexTreeEntry{Name: path.Base(node.Files[i].Path), File: &node.Files[i]})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name == entries[j].Name {
			return entries[i].IsDir && !entries[j].IsDir
		}
		return entries[i].Name < entries[j].Name
	})

	indent := strings.Repeat("  ", depth)
	for _, entry := range entries {
		if entry.IsDir {
			fmt.Fprintf(b, "%s- %s/\n", indent, entry.Name)
			renderIndexNode(b, entry.Dir, depth+1)
			continue
		}
		fmt.Fprintf(b, "%s- [%s](%s)\n", indent, entry.File.Title, entry.File.Path)
	}
}

func indexDocs(repo, dir string) ([]indexDoc, error) {
	root := filepath.Join(repo, dir)
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var docs []indexDoc
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		if strings.ToLower(filepath.Ext(entry.Name())) != ".md" {
			return nil
		}
		rel, err := filepath.Rel(repo, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		title, err := titleForFile(path, rel)
		if err != nil {
			return err
		}
		docs = append(docs, indexDoc{Path: rel, Title: title})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].Path < docs[j].Path })
	return docs, nil
}

func titleForFile(absPath, relPath string) (string, error) {
	content, err := os.ReadFile(absPath)
	if err != nil {
		return "", err
	}
	meta, body, hasFrontmatter, err := frontmatter.Split(content)
	if err == nil && hasFrontmatter && meta.Title != "" {
		return meta.Title, nil
	}
	if err != nil && hasFrontmatter {
		return "", fmt.Errorf("%s has invalid frontmatter: %w", relPath, err)
	}
	analysis, err := md.Analyze(relPath, body)
	if err != nil {
		return "", err
	}
	if analysis.FirstH1 != "" {
		return analysis.FirstH1, nil
	}
	base := filepath.Base(relPath)
	return strings.TrimSuffix(base, filepath.Ext(base)), nil
}

var changelogSubject = regexp.MustCompile(`^\[(source|create|append|update|delete|sync)\] \[[^]]+\]: .+$`)

func ChangelogForRepo(repo string, pending []PendingChangelogEntry) (string, error) {
	entries, err := changelogEntries(repo)
	if err != nil {
		return "", err
	}
	for _, entry := range pending {
		if strings.TrimSpace(entry.Subject) == "" {
			continue
		}
		date := entry.Date
		if date.IsZero() {
			date = time.Now()
		}
		entries = append(entries, date.Format("2006-01-02")+" "+entry.Subject)
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Changelog\n\n")
	b.WriteString("Generated from Lumbrera commit history.\n\n")
	if len(entries) == 0 {
		b.WriteString("No Lumbrera writes yet.\n")
		return b.String(), nil
	}
	for _, entry := range entries {
		b.WriteString(entry)
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func changelogEntries(repo string) ([]string, error) {
	if !git.HasCommits(repo) {
		return nil, nil
	}
	result, err := git.Run(repo, "log", "--reverse", "--date=short", "--format=%ad%x09%s")
	if err != nil {
		return nil, err
	}
	var entries []string
	for _, line := range strings.Split(strings.TrimSpace(result.Stdout), "\n") {
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, "\t", 2)
		if len(parts) != 2 || !changelogSubject.MatchString(parts[1]) {
			continue
		}
		entries = append(entries, parts[0]+" "+parts[1])
	}
	return entries, nil
}
