package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/javiermolinar/lumbrera/internal/frontmatter"
)

func TestIndexForRepoListsWikiPagesWithSources(t *testing.T) {
	repo := t.TempDir()
	writeRaw(t, repo, "sources/2026/05/04/raw.md", "# Raw source\n")
	writeRaw(t, repo, "sources/unreferenced.md", "# Unreferenced source\n")
	writeDoc(t, repo, "wiki/architecture/topic.md", frontmatter.New("wiki", "Topic title", "Topic summary.", []string{"design"}, []string{"sources/2026/05/04/raw.md"}, nil), "# Ignored wiki H1\n")

	index, err := IndexForRepo(repo)
	if err != nil {
		t.Fatal(err)
	}
	// INDEX.md is wiki-only; sources appear as sub-links.
	for _, want := range []string{
		"Wiki knowledge pages",
		"- architecture/\n  - [Topic title](wiki/architecture/topic.md)\n    - Sources: [Raw](sources/2026/05/04/raw.md)",
	} {
		if !strings.Contains(index, want) {
			t.Fatalf("expected index to contain %q, got:\n%s", want, index)
		}
	}
	// Sources should NOT appear as top-level entries in INDEX.md.
	if strings.Contains(index, "## Sources") {
		t.Fatalf("INDEX.md should not have a Sources section, got:\n%s", index)
	}
}

func TestSourcesIndexForRepoListsSources(t *testing.T) {
	repo := t.TempDir()
	writeRaw(t, repo, "sources/2026/05/04/raw.md", "# Raw source\n")
	writeRaw(t, repo, "sources/unreferenced.md", "# Unreferenced source\n")

	sources, err := SourcesIndexForRepo(repo)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"Immutable reference material",
		"[Raw source](sources/2026/05/04/raw.md)",
		"[Unreferenced source](sources/unreferenced.md)",
	} {
		if !strings.Contains(sources, want) {
			t.Fatalf("expected SOURCES.md to contain %q, got:\n%s", want, sources)
		}
	}
}

func TestAssetsIndexForRepoEmpty(t *testing.T) {
	repo := t.TempDir()

	assets, err := AssetsIndexForRepo(repo)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(assets, "No assets yet.") {
		t.Fatalf("expected empty assets placeholder, got:\n%s", assets)
	}
}

func TestTagsForRepoUsesWikiFrontmatter(t *testing.T) {
	repo := t.TempDir()
	writeDoc(t, repo, "wiki/architecture/topic.md", frontmatter.New("wiki", "Topic title", "Topic summary.", []string{"design", "architecture"}, []string{"sources/raw.md"}, nil), "# Topic title\n")
	writeDoc(t, repo, "wiki/runbooks/fix.md", frontmatter.New("wiki", "Fix", "Fix summary.", []string{"runbook"}, []string{"sources/fix.md"}, nil), "# Fix\n")

	tags, err := TagsForRepo(repo)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"Generated by Lumbrera from wiki frontmatter. Agents must not edit this file.",
		"## Tags",
		"- architecture (1)",
		"- design (1)",
		"- runbook (1)",
	} {
		if !strings.Contains(tags, want) {
			t.Fatalf("expected tags to contain %q, got:\n%s", want, tags)
		}
	}
	for _, unwanted := range []string{"wiki/architecture/topic.md", "Topic summary.", "wiki/runbooks/fix.md"} {
		if strings.Contains(tags, unwanted) {
			t.Fatalf("expected compact tags file not to contain %q, got:\n%s", unwanted, tags)
		}
	}
}

func writeRaw(t *testing.T, repo, rel, content string) {
	t.Helper()
	path := filepath.Join(repo, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeDoc(t *testing.T, repo, rel string, meta frontmatter.Document, body string) {
	t.Helper()
	content, err := frontmatter.Attach(meta, body)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(repo, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
