package generate

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/javiermolinar/lumbrera/internal/brain"
	"github.com/javiermolinar/lumbrera/internal/frontmatter"
	"github.com/javiermolinar/lumbrera/internal/manifest"
	md "github.com/javiermolinar/lumbrera/internal/markdown"
	"github.com/javiermolinar/lumbrera/internal/ops"
)

type Files struct {
	Index     string
	Changelog string
	BrainSum  string
	Tags      string
}

func FilesForRepo(repo string) (Files, error) {
	index, err := IndexForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	changelog, err := ChangelogForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	brainSum, err := manifest.ForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	tags, err := TagsForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	return Files{Index: index, Changelog: changelog, BrainSum: brainSum, Tags: tags}, nil
}

func WriteFiles(repo string, files Files) error {
	if err := os.WriteFile(filepath.Join(repo, brain.IndexPath), []byte(files.Index), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(repo, brain.ChangelogPath), []byte(files.Changelog), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(repo, brain.BrainSumPath), []byte(files.BrainSum), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(repo, brain.TagsPath), []byte(files.Tags), 0o644)
}

type indexDoc struct {
	Path  string
	Title string
}

func IndexForRepo(repo string) (string, error) {
	sources, err := sourceIndexDocsFromWiki(repo)
	if err != nil {
		return "", err
	}
	wiki, err := indexDocs(repo, "wiki")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Index\n\n")
	b.WriteString("Generated by Lumbrera.\n\n")
	b.WriteString("## Sources\n\n")
	writeIndexTree(&b, "sources", sources, "No sources yet.")
	b.WriteString("\n## Wiki\n\n")
	writeIndexTree(&b, "wiki", wiki, "No wiki pages yet.")
	return b.String(), nil
}

func TagsForRepo(repo string) (string, error) {
	tags, err := tagDocsFromWiki(repo)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Tags\n\n")
	b.WriteString("Generated by Lumbrera from wiki frontmatter. Agents must not edit this file.\n\n")
	b.WriteString(fmt.Sprintf("Wiki pages require 1-%d lowercase slug tags. Reuse existing tags when they fit.\n", frontmatter.MaxTags))
	if len(tags) == 0 {
		b.WriteString("\nNo tags yet.\n")
		return b.String(), nil
	}

	b.WriteString("\n## Tags\n\n")
	keys := make([]string, 0, len(tags))
	for tag := range tags {
		keys = append(keys, tag)
	}
	sort.Strings(keys)
	for _, tag := range keys {
		fmt.Fprintf(&b, "- %s (%d)\n", tag, tags[tag])
	}
	return b.String(), nil
}

type indexNode struct {
	Dirs  map[string]*indexNode
	Files []indexDoc
}

func newIndexNode() *indexNode {
	return &indexNode{Dirs: map[string]*indexNode{}}
}

func writeIndexTree(b *strings.Builder, root string, docs []indexDoc, emptyMessage string) {
	if len(docs) == 0 {
		b.WriteString(emptyMessage)
		b.WriteByte('\n')
		return
	}

	tree := newIndexNode()
	for _, doc := range docs {
		rel := strings.TrimPrefix(doc.Path, root+"/")
		parts := strings.Split(rel, "/")
		node := tree
		for _, dir := range parts[:len(parts)-1] {
			if dir == "" {
				continue
			}
			next := node.Dirs[dir]
			if next == nil {
				next = newIndexNode()
				node.Dirs[dir] = next
			}
			node = next
		}
		node.Files = append(node.Files, doc)
	}
	renderIndexNode(b, tree, 0)
}

type indexTreeEntry struct {
	Name  string
	Dir   *indexNode
	File  *indexDoc
	IsDir bool
}

func renderIndexNode(b *strings.Builder, node *indexNode, depth int) {
	entries := make([]indexTreeEntry, 0, len(node.Dirs)+len(node.Files))
	for name, dir := range node.Dirs {
		entries = append(entries, indexTreeEntry{Name: name, Dir: dir, IsDir: true})
	}
	for i := range node.Files {
		entries = append(entries, indexTreeEntry{Name: path.Base(node.Files[i].Path), File: &node.Files[i]})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name == entries[j].Name {
			return entries[i].IsDir && !entries[j].IsDir
		}
		return entries[i].Name < entries[j].Name
	})

	indent := strings.Repeat("  ", depth)
	for _, entry := range entries {
		if entry.IsDir {
			fmt.Fprintf(b, "%s- %s/\n", indent, entry.Name)
			renderIndexNode(b, entry.Dir, depth+1)
			continue
		}
		fmt.Fprintf(b, "%s- [%s](%s)\n", indent, entry.File.Title, entry.File.Path)
	}
}

func indexDocs(repo, dir string) ([]indexDoc, error) {
	root := filepath.Join(repo, dir)
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var docs []indexDoc
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		if strings.ToLower(filepath.Ext(entry.Name())) != ".md" {
			return nil
		}
		rel, err := filepath.Rel(repo, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		title, err := titleForFile(path, rel)
		if err != nil {
			return err
		}
		docs = append(docs, indexDoc{Path: rel, Title: title})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].Path < docs[j].Path })
	return docs, nil
}

func sourceIndexDocsFromWiki(repo string) ([]indexDoc, error) {
	root := filepath.Join(repo, "wiki")
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	seen := map[string]struct{}{}
	var docs []indexDoc
	err := walkWikiMetadata(repo, func(rel string, meta frontmatter.Document) error {
		for _, source := range meta.Lumbrera.Sources {
			if !strings.HasPrefix(source, "sources/") {
				continue
			}
			if _, ok := seen[source]; ok {
				continue
			}
			seen[source] = struct{}{}
			docs = append(docs, indexDoc{Path: source, Title: titleForPath(source)})
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].Path < docs[j].Path })
	return docs, nil
}

func tagDocsFromWiki(repo string) (map[string]int, error) {
	tags := map[string]int{}
	err := walkWikiMetadata(repo, func(rel string, meta frontmatter.Document) error {
		_ = rel
		for _, tag := range meta.Tags {
			tags[tag]++
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return tags, nil
}

func walkWikiMetadata(repo string, visit func(rel string, meta frontmatter.Document) error) error {
	root := filepath.Join(repo, "wiki")
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	return filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || strings.ToLower(filepath.Ext(entry.Name())) != ".md" {
			return nil
		}
		rel, err := filepath.Rel(repo, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		meta, _, hasFrontmatter, err := frontmatter.Split(content)
		if err != nil {
			return fmt.Errorf("%s has invalid frontmatter: %w", rel, err)
		}
		if !hasFrontmatter {
			return nil
		}
		return visit(rel, meta)
	})
}

func titleForFile(absPath, relPath string) (string, error) {
	content, err := os.ReadFile(absPath)
	if err != nil {
		return "", err
	}
	meta, body, hasFrontmatter, err := frontmatter.Split(content)
	if err == nil && hasFrontmatter && meta.Title != "" {
		return meta.Title, nil
	}
	if err != nil && hasFrontmatter {
		return "", fmt.Errorf("%s has invalid frontmatter: %w", relPath, err)
	}
	analysis, err := md.AnalyzeWithOptions(relPath, body, md.AnalyzeOptions{})
	if err != nil {
		return "", err
	}
	if analysis.FirstH1 != "" {
		return analysis.FirstH1, nil
	}
	return titleForPath(relPath), nil
}

func titleForPath(relPath string) string {
	base := filepath.Base(relPath)
	base = strings.TrimSuffix(base, filepath.Ext(base))
	base = strings.ReplaceAll(base, "-", " ")
	base = strings.ReplaceAll(base, "_", " ")
	base = strings.TrimSpace(base)
	if base == "" {
		return relPath
	}
	return titleWords(base)
}

func titleWords(value string) string {
	parts := strings.Fields(value)
	for i, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		parts[i] = string(runes)
	}
	return strings.Join(parts, " ")
}

func ChangelogForRepo(repo string) (string, error) {
	entries, err := ops.Read(repo)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Changelog\n\n")
	b.WriteString("Generated from the Lumbrera operation log.\n\n")
	if len(entries) == 0 {
		b.WriteString("No Lumbrera writes yet.\n")
		return b.String(), nil
	}
	for _, entry := range entries {
		b.WriteString(ops.ChangelogLine(entry))
		b.WriteByte('\n')
	}
	return b.String(), nil
}
