package generate

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/javiermolinar/lumbrera/internal/brainfs"
	"github.com/javiermolinar/lumbrera/internal/frontmatter"
	md "github.com/javiermolinar/lumbrera/internal/markdown"
	"github.com/javiermolinar/lumbrera/internal/textutil"
)

type indexDoc struct {
	Path  string
	Title string
}

func IndexForRepo(repo string) (string, error) {
	sources, err := indexDocs(repo, "sources")
	if err != nil {
		return "", err
	}
	wiki, err := indexDocs(repo, "wiki")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Index\n\n")
	b.WriteString("Generated by Lumbrera.\n\n")
	b.WriteString("## Sources\n\n")
	writeIndexTree(&b, "sources", sources, "No sources yet.")
	b.WriteString("\n## Wiki\n\n")
	writeIndexTree(&b, "wiki", wiki, "No wiki pages yet.")
	return b.String(), nil
}

type indexNode struct {
	Dirs  map[string]*indexNode
	Files []indexDoc
}

func newIndexNode() *indexNode {
	return &indexNode{Dirs: map[string]*indexNode{}}
}

func writeIndexTree(b *strings.Builder, root string, docs []indexDoc, emptyMessage string) {
	if len(docs) == 0 {
		b.WriteString(emptyMessage)
		b.WriteByte('\n')
		return
	}

	tree := newIndexNode()
	for _, doc := range docs {
		rel := strings.TrimPrefix(doc.Path, root+"/")
		parts := strings.Split(rel, "/")
		node := tree
		for _, dir := range parts[:len(parts)-1] {
			if dir == "" {
				continue
			}
			next := node.Dirs[dir]
			if next == nil {
				next = newIndexNode()
				node.Dirs[dir] = next
			}
			node = next
		}
		node.Files = append(node.Files, doc)
	}
	renderIndexNode(b, tree, 0)
}

type indexTreeEntry struct {
	Name  string
	Dir   *indexNode
	File  *indexDoc
	IsDir bool
}

func renderIndexNode(b *strings.Builder, node *indexNode, depth int) {
	entries := make([]indexTreeEntry, 0, len(node.Dirs)+len(node.Files))
	for name, dir := range node.Dirs {
		entries = append(entries, indexTreeEntry{Name: name, Dir: dir, IsDir: true})
	}
	for i := range node.Files {
		entries = append(entries, indexTreeEntry{Name: path.Base(node.Files[i].Path), File: &node.Files[i]})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name == entries[j].Name {
			return entries[i].IsDir && !entries[j].IsDir
		}
		return entries[i].Name < entries[j].Name
	})

	indent := strings.Repeat("  ", depth)
	for _, entry := range entries {
		if entry.IsDir {
			fmt.Fprintf(b, "%s- %s/\n", indent, entry.Name)
			renderIndexNode(b, entry.Dir, depth+1)
			continue
		}
		fmt.Fprintf(b, "%s- [%s](%s)\n", indent, entry.File.Title, entry.File.Path)
	}
}

func indexDocs(repo, dir string) ([]indexDoc, error) {
	paths, err := brainfs.MarkdownPaths(repo, []string{dir})
	if err != nil {
		return nil, err
	}

	docs := make([]indexDoc, 0, len(paths))
	for _, rel := range paths {
		title, err := titleForFile(filepath.Join(repo, filepath.FromSlash(rel)), rel)
		if err != nil {
			return nil, err
		}
		docs = append(docs, indexDoc{Path: rel, Title: title})
	}
	return docs, nil
}

func sourceIndexDocsFromWiki(repo string) ([]indexDoc, error) {
	seen := map[string]struct{}{}
	var docs []indexDoc
	err := walkWikiMetadata(repo, func(rel string, meta frontmatter.Document) error {
		for _, source := range meta.Lumbrera.Sources {
			if !strings.HasPrefix(source, "sources/") {
				continue
			}
			if _, ok := seen[source]; ok {
				continue
			}
			seen[source] = struct{}{}
			docs = append(docs, indexDoc{Path: source, Title: titleForPath(source)})
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].Path < docs[j].Path })
	return docs, nil
}

func titleForFile(absPath, relPath string) (string, error) {
	content, err := os.ReadFile(absPath)
	if err != nil {
		return "", err
	}
	meta, body, hasFrontmatter, err := frontmatter.Split(content)
	if err == nil && hasFrontmatter && meta.Title != "" {
		return meta.Title, nil
	}
	if err != nil && hasFrontmatter {
		return "", fmt.Errorf("%s has invalid frontmatter: %w", relPath, err)
	}
	analysis, err := md.AnalyzeWithOptions(relPath, body, md.AnalyzeOptions{IgnoreLinks: true})
	if err != nil {
		return "", err
	}
	if analysis.FirstH1 != "" {
		return analysis.FirstH1, nil
	}
	return titleForPath(relPath), nil
}

func titleForPath(relPath string) string {
	return textutil.TitleForPath(relPath)
}
