package generate

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/javiermolinar/lumbrera/internal/brainfs"
	"github.com/javiermolinar/lumbrera/internal/frontmatter"
	md "github.com/javiermolinar/lumbrera/internal/markdown"
	"github.com/javiermolinar/lumbrera/internal/textutil"
)

type indexDoc struct {
	Path  string
	Title string
}

// wikiDocWithSources holds a wiki index entry and its backing sources.
type wikiDocWithSources struct {
	indexDoc
	Sources []indexDoc
}

// IndexForRepo generates INDEX.md containing only wiki pages, each with
// sub-links to its backing sources.
func IndexForRepo(repo string) (string, error) {
	wikiDocs, err := wikiDocsWithSources(repo)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Index\n\n")
	b.WriteString("Generated by Lumbrera. Wiki knowledge pages.\n\n")
	writeWikiIndexTree(&b, wikiDocs, "No wiki pages yet.")
	return b.String(), nil
}

// SourcesIndexForRepo generates SOURCES.md listing all source files.
func SourcesIndexForRepo(repo string) (string, error) {
	sources, err := indexDocs(repo, "sources")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Sources\n\n")
	b.WriteString("Generated by Lumbrera. Immutable reference material.\n\n")
	writeIndexTree(&b, "sources", sources, "No sources yet.")
	return b.String(), nil
}

// AssetsIndexForRepo generates ASSETS.md listing all asset files.
func AssetsIndexForRepo(repo string) (string, error) {
	assets, err := assetDocs(repo)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Assets\n\n")
	b.WriteString("Generated by Lumbrera. Immutable binary attachments.\n\n")
	writeIndexTree(&b, "assets", assets, "No assets yet.")
	return b.String(), nil
}

type indexNode struct {
	Dirs  map[string]*indexNode
	Files []indexDoc
}

func newIndexNode() *indexNode {
	return &indexNode{Dirs: map[string]*indexNode{}}
}

func writeIndexTree(b *strings.Builder, root string, docs []indexDoc, emptyMessage string) {
	if len(docs) == 0 {
		b.WriteString(emptyMessage)
		b.WriteByte('\n')
		return
	}

	tree := newIndexNode()
	for _, doc := range docs {
		rel := strings.TrimPrefix(doc.Path, root+"/")
		parts := strings.Split(rel, "/")
		node := tree
		for _, dir := range parts[:len(parts)-1] {
			if dir == "" {
				continue
			}
			next := node.Dirs[dir]
			if next == nil {
				next = newIndexNode()
				node.Dirs[dir] = next
			}
			node = next
		}
		node.Files = append(node.Files, doc)
	}
	renderIndexNode(b, tree, 0)
}

type indexTreeEntry struct {
	Name  string
	Dir   *indexNode
	File  *indexDoc
	IsDir bool
}

// wikiIndexNode extends indexNode with source sub-links per file.
type wikiIndexNode struct {
	Dirs  map[string]*wikiIndexNode
	Files []wikiDocWithSources
}

func newWikiIndexNode() *wikiIndexNode {
	return &wikiIndexNode{Dirs: map[string]*wikiIndexNode{}}
}

func writeWikiIndexTree(b *strings.Builder, docs []wikiDocWithSources, emptyMessage string) {
	if len(docs) == 0 {
		b.WriteString(emptyMessage)
		b.WriteByte('\n')
		return
	}

	tree := newWikiIndexNode()
	for _, doc := range docs {
		rel := strings.TrimPrefix(doc.Path, "wiki/")
		parts := strings.Split(rel, "/")
		node := tree
		for _, dir := range parts[:len(parts)-1] {
			if dir == "" {
				continue
			}
			next := node.Dirs[dir]
			if next == nil {
				next = newWikiIndexNode()
				node.Dirs[dir] = next
			}
			node = next
		}
		node.Files = append(node.Files, doc)
	}
	renderWikiIndexNode(b, tree, 0)
}

type wikiIndexTreeEntry struct {
	Name  string
	Dir   *wikiIndexNode
	File  *wikiDocWithSources
	IsDir bool
}

func renderWikiIndexNode(b *strings.Builder, node *wikiIndexNode, depth int) {
	entries := make([]wikiIndexTreeEntry, 0, len(node.Dirs)+len(node.Files))
	for name, dir := range node.Dirs {
		entries = append(entries, wikiIndexTreeEntry{Name: name, Dir: dir, IsDir: true})
	}
	for i := range node.Files {
		entries = append(entries, wikiIndexTreeEntry{Name: path.Base(node.Files[i].Path), File: &node.Files[i]})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name == entries[j].Name {
			return entries[i].IsDir && !entries[j].IsDir
		}
		return entries[i].Name < entries[j].Name
	})

	indent := strings.Repeat("  ", depth)
	for _, entry := range entries {
		if entry.IsDir {
			fmt.Fprintf(b, "%s- %s/\n", indent, entry.Name)
			renderWikiIndexNode(b, entry.Dir, depth+1)
			continue
		}
		fmt.Fprintf(b, "%s- [%s](%s)\n", indent, entry.File.Title, entry.File.Path)
		if len(entry.File.Sources) > 0 {
			var links []string
			for _, src := range entry.File.Sources {
				links = append(links, fmt.Sprintf("[%s](%s)", src.Title, src.Path))
			}
			fmt.Fprintf(b, "%s  - Sources: %s\n", indent, strings.Join(links, ", "))
		}
	}
}

func renderIndexNode(b *strings.Builder, node *indexNode, depth int) {
	entries := make([]indexTreeEntry, 0, len(node.Dirs)+len(node.Files))
	for name, dir := range node.Dirs {
		entries = append(entries, indexTreeEntry{Name: name, Dir: dir, IsDir: true})
	}
	for i := range node.Files {
		entries = append(entries, indexTreeEntry{Name: path.Base(node.Files[i].Path), File: &node.Files[i]})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Name == entries[j].Name {
			return entries[i].IsDir && !entries[j].IsDir
		}
		return entries[i].Name < entries[j].Name
	})

	indent := strings.Repeat("  ", depth)
	for _, entry := range entries {
		if entry.IsDir {
			fmt.Fprintf(b, "%s- %s/\n", indent, entry.Name)
			renderIndexNode(b, entry.Dir, depth+1)
			continue
		}
		fmt.Fprintf(b, "%s- [%s](%s)\n", indent, entry.File.Title, entry.File.Path)
	}
}

func indexDocs(repo, dir string) ([]indexDoc, error) {
	paths, err := brainfs.MarkdownPaths(repo, []string{dir})
	if err != nil {
		return nil, err
	}

	docs := make([]indexDoc, 0, len(paths))
	for _, rel := range paths {
		title, err := titleForFile(filepath.Join(repo, filepath.FromSlash(rel)), rel)
		if err != nil {
			return nil, err
		}
		docs = append(docs, indexDoc{Path: rel, Title: title})
	}
	return docs, nil
}

func sourceIndexDocsFromWiki(repo string) ([]indexDoc, error) {
	seen := map[string]struct{}{}
	var docs []indexDoc
	err := walkWikiMetadata(repo, func(rel string, meta frontmatter.Document) error {
		for _, source := range meta.Lumbrera.Sources {
			if !strings.HasPrefix(source, "sources/") {
				continue
			}
			if _, ok := seen[source]; ok {
				continue
			}
			seen[source] = struct{}{}
			docs = append(docs, indexDoc{Path: source, Title: titleForPath(source)})
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].Path < docs[j].Path })
	return docs, nil
}

func titleForFile(absPath, relPath string) (string, error) {
	content, err := os.ReadFile(absPath)
	if err != nil {
		return "", err
	}
	meta, body, hasFrontmatter, err := frontmatter.Split(content)
	if err == nil && hasFrontmatter && meta.Title != "" {
		return meta.Title, nil
	}
	if err != nil && hasFrontmatter {
		return "", fmt.Errorf("%s has invalid frontmatter: %w", relPath, err)
	}
	analysis, err := md.AnalyzeWithOptions(relPath, body, md.AnalyzeOptions{IgnoreLinks: true})
	if err != nil {
		return "", err
	}
	if analysis.FirstH1 != "" {
		return analysis.FirstH1, nil
	}
	return titleForPath(relPath), nil
}

func titleForPath(relPath string) string {
	return textutil.TitleForPath(relPath)
}

// wikiDocsWithSources builds wiki index entries with their backing sources.
func wikiDocsWithSources(repo string) ([]wikiDocWithSources, error) {
	var docs []wikiDocWithSources
	err := walkWikiMetadata(repo, func(rel string, meta frontmatter.Document) error {
		title := meta.Title
		if title == "" {
			title = titleForPath(rel)
		}
		doc := wikiDocWithSources{
			indexDoc: indexDoc{Path: rel, Title: title},
		}
		for _, src := range meta.Lumbrera.Sources {
			doc.Sources = append(doc.Sources, indexDoc{
				Path:  src,
				Title: titleForPath(src),
			})
		}
		sort.Slice(doc.Sources, func(i, j int) bool { return doc.Sources[i].Path < doc.Sources[j].Path })
		docs = append(docs, doc)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].Path < docs[j].Path })
	return docs, nil
}

// assetDocs lists all files under assets/ for the assets index.
func assetDocs(repo string) ([]indexDoc, error) {
	assetsDir := filepath.Join(repo, "assets")
	info, err := os.Lstat(assetsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	if !info.IsDir() {
		return nil, nil
	}

	var docs []indexDoc
	err = filepath.WalkDir(assetsDir, func(absPath string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(repo, absPath)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		docs = append(docs, indexDoc{Path: rel, Title: path.Base(rel)})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(docs, func(i, j int) bool { return docs[i].Path < docs[j].Path })
	return docs, nil
}
