package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/javiermolinar/lumbrera/internal/brain"
	"github.com/javiermolinar/lumbrera/internal/frontmatter"
	"github.com/javiermolinar/lumbrera/internal/manifest"
)

// FilesForRepoVersion generates the closed derived-file contract for a
// supported brain version. Older formats exist only for migration preflight and
// ordered migration steps.
func FilesForRepoVersion(repo, version string) (Files, error) {
	switch version {
	case brain.Version:
		return FilesForRepo(repo)
	case brain.VersionV2:
		return filesForRepoV2(repo)
	case brain.VersionV1:
		return filesForRepoV1(repo)
	default:
		return Files{}, fmt.Errorf("unsupported Lumbrera brain version %q", version)
	}
}

func GeneratedPathsForVersion(version string) ([]string, error) {
	switch version {
	case brain.Version:
		return brain.GeneratedFilePaths(), nil
	case brain.VersionV2:
		return []string{brain.IndexPath, brain.SourcesIndexPath, brain.AssetsIndexPath, brain.BrainSumPath, brain.TagsPath}, nil
	case brain.VersionV1:
		return []string{brain.IndexPath, brain.BrainSumPath, brain.TagsPath}, nil
	default:
		return nil, fmt.Errorf("unsupported Lumbrera brain version %q", version)
	}
}

func WriteFilesForVersion(repo, version string, files Files) error {
	paths, err := GeneratedPathsForVersion(version)
	if err != nil {
		return err
	}
	content := map[string]string{
		brain.IndexPath:        files.Index,
		brain.SourcesIndexPath: files.SourcesIndex,
		brain.NotesIndexPath:   files.NotesIndex,
		brain.AssetsIndexPath:  files.AssetsIndex,
		brain.BrainSumPath:     files.BrainSum,
		brain.TagsPath:         files.Tags,
	}
	for _, rel := range paths {
		if err := os.WriteFile(filepath.Join(repo, filepath.FromSlash(rel)), []byte(content[rel]), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func filesForRepoV2(repo string) (Files, error) {
	index, err := IndexForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	sources, err := SourcesIndexForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	assets, err := AssetsIndexForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	brainSum, err := manifest.ForRoots(repo, []string{"wiki"})
	if err != nil {
		return Files{}, err
	}
	tags, err := legacyTagsForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	return Files{Index: index, SourcesIndex: sources, AssetsIndex: assets, BrainSum: brainSum, Tags: tags}, nil
}

func filesForRepoV1(repo string) (Files, error) {
	index, err := legacyV1IndexForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	brainSum, err := manifest.ForRoots(repo, []string{"wiki"})
	if err != nil {
		return Files{}, err
	}
	tags, err := legacyTagsForRepo(repo)
	if err != nil {
		return Files{}, err
	}
	return Files{Index: index, BrainSum: brainSum, Tags: tags}, nil
}

func legacyV1IndexForRepo(repo string) (string, error) {
	sources, err := indexDocs(repo, "sources")
	if err != nil {
		return "", err
	}
	wiki, err := indexDocs(repo, "wiki")
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# Lumbrera Index\n\n")
	b.WriteString("Generated by Lumbrera.\n\n")
	b.WriteString("## Sources\n\n")
	writeIndexTree(&b, "sources", sources, "No sources yet.")
	b.WriteString("\n## Wiki\n\n")
	writeIndexTree(&b, "wiki", wiki, "No wiki pages yet.")
	return b.String(), nil
}

func legacyTagsForRepo(repo string) (string, error) {
	tags := map[string]int{}
	if err := walkWikiMetadata(repo, func(_ string, meta frontmatter.Document) error {
		for _, tag := range meta.Tags {
			tags[tag]++
		}
		return nil
	}); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Tags\n\n")
	b.WriteString("Generated by Lumbrera from wiki frontmatter. Agents must not edit this file.\n\n")
	fmt.Fprintf(&b, "Wiki pages require 1-%d lowercase slug tags. Reuse existing tags when they fit.\n", frontmatter.MaxTags)
	if len(tags) == 0 {
		b.WriteString("\nNo tags yet.\n")
		return b.String(), nil
	}
	b.WriteString("\n## Tags\n\n")
	keys := make([]string, 0, len(tags))
	for tag := range tags {
		keys = append(keys, tag)
	}
	sort.Strings(keys)
	for _, tag := range keys {
		fmt.Fprintf(&b, "- %s (%d)\n", tag, tags[tag])
	}
	return b.String(), nil
}
