package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/javiermolinar/lumbrera/internal/frontmatter"
)

func TagsForRepo(repo string) (string, error) {
	tags, err := tagDocsFromWiki(repo)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Lumbrera Tags\n\n")
	b.WriteString("Generated by Lumbrera from wiki frontmatter. Agents must not edit this file.\n\n")
	b.WriteString(fmt.Sprintf("Wiki pages require 1-%d lowercase slug tags. Reuse existing tags when they fit.\n", frontmatter.MaxTags))
	if len(tags) == 0 {
		b.WriteString("\nNo tags yet.\n")
		return b.String(), nil
	}

	b.WriteString("\n## Tags\n\n")
	keys := make([]string, 0, len(tags))
	for tag := range tags {
		keys = append(keys, tag)
	}
	sort.Strings(keys)
	for _, tag := range keys {
		fmt.Fprintf(&b, "- %s (%d)\n", tag, tags[tag])
	}
	return b.String(), nil
}

func tagDocsFromWiki(repo string) (map[string]int, error) {
	tags := map[string]int{}
	err := walkWikiMetadata(repo, func(rel string, meta frontmatter.Document) error {
		_ = rel
		for _, tag := range meta.Tags {
			tags[tag]++
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return tags, nil
}
